apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend-np
spec:
  ports:
  - name: 80-8000
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: frontend
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: frontend-ing
spec:
  rules:
  - http:
      paths:
      - backend:
          service:
            name: frontend-np
            port:
              number: 80
        path: /
        pathType: Exact
status:
  loadBalancer: {}
